[package]
name = "pso-rs"
version = "0.1.0"
authors = ["Christos Zonios <czonios@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
indicatif = "0.16.2"
